const EMPLOYEE_ROLES = {
  INTERN: "INTERN",
  EMPLOYEE: "EMPLOYEE",
  MANAGER: "MANAGER",
  SENIOR_MANAGER: "SENIOR_MANAGER",
};

export const EmployeeConstants = {
  EMPLOYEE_ROLES,
};

export const DEFAULT_ALLOWED_ROLES = [
  EmployeeConstants.EMPLOYEE_ROLES.INTERN,
  EmployeeConstants.EMPLOYEE_ROLES.EMPLOYEE,
  EmployeeConstants.EMPLOYEE_ROLES.MANAGER,
  EmployeeConstants.EMPLOYEE_ROLES.SENIOR_MANAGER,
];
